export const AUTH_USER_CHANGE = 'AUTH/AUTH_USER_CHANGE'
export const USER_EMAIL_CHANGE = 'AUTH/USER_EMAIL_CHANGE'
export const USER_PASSWORD_CHANGE = 'AUTH/USER_PASSWORD_CHANGE'

export const SIGN_UP_REQUEST = 'AUTH/SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'AUTH/SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR = 'AUTH/SIGN_UP_ERROR'

