export const LOAD_ALL_MOVIES_START = 'FILMS/LOAD_ALL_MOVIES_START'
export const LOAD_ALL_MOVIES_SUCCESS = 'FILMS/LOAD_ALL_MOVIES_SUCCESS'
export const LOAD_ALL_MOVIES_FAIL = 'FILMS/LOAD_ALL_MOVIES_FAIL'

export const LOAD_MORE_START = 'FILMS/LOAD_MORE_START'
export const LOAD_MORE_SUCCESS = 'FILMS/LOAD_MORE_SUCCESS'
export const LOAD_MORE_FAIL = 'FILMS/LOAD_MORE_FAIL'

export const CHANGE_LOAD_MORE_COUNT = 'FILMS/CHANGE_LOAD_MORE_COUNT'
export const CHANGE_SEARCH_TITLE = 'FILMS/CHANGE_SEARCH_TITLE'

export const moduleName = 'movieList'